# ==============================================
# Kubernetes Secret for PostgreSQL
# ==============================================
# What is this?
# A Secret stores sensitive data like passwords in Kubernetes
# Data is base64 encoded (NOT encrypted - just encoded!)
# Real security comes from Kubernetes RBAC (Role-Based Access Control)

# How to apply:
# kubectl apply -f infra/1-postgres-secret.yaml

# How to view (decoded):
# kubectl get secret postgres-secret -o jsonpath='{.data.postgres-password}' | base64 -d

# How to delete:
# kubectl delete secret postgres-secret
# ==============================================

apiVersion: v1
kind: Secret
metadata:
  # Name of the secret (we'll reference this in the deployment)
  name: postgres-secret

  # Namespace (default = main namespace)
  namespace: default

  # Labels for organization (optional but useful)
  labels:
    app: postgres
    component: database

# Type of secret
# Opaque = generic secret (most common type)
type: Opaque

# Data section - all values must be base64 encoded
# To encode: echo -n "your-value" | base64
# To decode: echo "encoded-value" | base64 -d
data:
  # PostgreSQL username: "postgres"
  # Base64: echo -n "postgres" | base64
  postgres-user: cG9zdGdyZXM=

  # PostgreSQL password: "kibo_password"
  # Base64: echo -n "kibo_password" | base64
  postgres-password: a2liby1wYXNzd29yZA==

  # PostgreSQL database name: "bidding_db"
  # Base64: echo -n "bidding_db" | base64
  postgres-db: YmlkZGluZ19kYg==

# ==============================================
# How this Secret is used:
# ==============================================
# In postgres-deployment.yaml, we reference it like this:
#
# env:
#   - name: POSTGRES_USER
#     valueFrom:
#       secretKeyRef:
#         name: postgres-secret      # This secret
#         key: postgres-user         # This key
#
# Kubernetes automatically decodes base64 and injects the value!
# ==============================================
