# ==============================================
# Kubernetes Secret for NestJS App
# ==============================================
# What is this?
# Secret stores SENSITIVE data like passwords and API keys
# Data is base64 encoded (NOT encrypted - just encoded!)
# Think: Locked safe - only authorized pods can access

# How to apply:
# kubectl apply -f infra/6-app-secret.yaml

# How to check:
# kubectl get secret app-secret
# kubectl describe secret app-secret  (doesn't show values)

# How to view (decoded):
# kubectl get secret app-secret -o jsonpath='{.data.KINDE_CLIENT_SECRET}' | base64 -d

# How to delete:
# kubectl delete secret app-secret
# ==============================================

apiVersion: v1
kind: Secret
metadata:
  # Name of the secret (we'll reference this in deployment)
  name: app-secret

  # Namespace
  namespace: default

  # Labels for organization
  labels:
    app: biddingservice
    component: backend

# Type of secret
type: Opaque

# ==============================================
# Data: All values MUST be base64 encoded
# ==============================================
# To encode: echo -n "your-value" | base64
# To decode: echo "encoded-value" | base64 -d
data:
  # Kinde Client ID: "da1058d120914598aaae2d460c519278"
  # Base64: echo -n "da1058d120914598aaae2d460c519278" | base64
  KINDE_CLIENT_ID: ZGExMDU4ZDEyMDkxNDU5OGFhYWUyZDQ2MGM1MTkyNzg=

  # Kinde Client Secret: "cx5dq6QTl5qcGqfDHA45IgmkTpm0AYkwzCFyGJVyUnQYdyiFXnC"
  # Base64: echo -n "cx5dq6QTl5qcGqfDHA45IgmkTpm0AYkwzCFyGJVyUnQYdyiFXnC" | base64
  KINDE_CLIENT_SECRET: Y3g1ZHE2UVRsNXFjR3FmREhBNDVJZ21rVHBtMEFZa3d6Q0Z5R0pWeVVuUVlkeWlGWG5D

# ==============================================
# How this Secret is used:
# ==============================================
# In app-deployment.yaml, we reference it like this:
#
# Method 1: Load all keys as env vars
# envFrom:
#   - secretRef:
#       name: app-secret
#
# Method 2: Load specific keys
# env:
#   - name: KINDE_CLIENT_ID
#     valueFrom:
#       secretKeyRef:
#         name: app-secret
#         key: KINDE_CLIENT_ID
#
# Kubernetes automatically decodes base64 and injects as env vars!
# ==============================================

# ==============================================
# Security Best Practices:
# ==============================================
# 1. NEVER commit real secrets to git!
#    - Use template files with placeholders
#    - Or use external secret managers (AWS Secrets Manager, HashiCorp Vault)
#
# 2. Encrypt Secrets at rest:
#    - Enable encryption in Kubernetes cluster
#    - kubectl create secret --dry-run=client -o yaml > secret.yaml
#
# 3. Use RBAC to control who can read secrets:
#    - Only authorized service accounts can access
#
# 4. Rotate secrets regularly:
#    - Update the base64 values
#    - kubectl apply -f 6-app-secret.yaml
#    - Restart pods to pick up new values
#
# 5. For production, consider:
#    - External Secrets Operator (syncs from cloud providers)
#    - Sealed Secrets (encrypt secrets in git)
#    - HashiCorp Vault integration
# ==============================================

# ==============================================
# How to create your own base64 values:
# ==============================================
# macOS/Linux:
# echo -n "your-secret-value" | base64
#
# Decode:
# echo "ZW5jb2RlZC12YWx1ZQ==" | base64 -d
#
# IMPORTANT: Use -n flag to avoid newline in encoding!
# ==============================================
